memeProject/memeCoreApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'memes'

urlpatterns = [
    path('', meme_list, name='meme-list'),
    path('<int:my_id>', upload_meme, name='upload_meme'),
    path('memes/<int:my_id>', memeDetail, name='meme-detail'),
    path('like/', like_meme, name='like-meme'),
    ]

memeProject/memeProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from register import views as register_views
from memeCoreApp.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', get_context_data, name='search'),
    path('', include('memeCoreApp.urls', namespace='memes')),
    path('memes/upload/', upload_meme, name='upload_meme'),
    path('memes/<int:my_id>', memeDetail, name='meme-detail'),
    path('memes/', meme_list, name='meme_list'),
    path('register/', register_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/', register_views.profile, name='profile'),
    path('category/nerd/', cat_nerd),
    path('category/dailystruggle/', cat_dailystruggle),
    path('category/programming/', cat_programming),
    path('category/quotes/', cat_quotes),
    path('mostliked/', count_likes),
    path('mostcommented', count_comments)
]

"""The following commands are needed to upload and store media"""
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # URL Patterns for profile pics
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # URL Patterns for static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memeProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="shortcut icon" type="image/png" href="{% static 'images/Logo_Three_square_gag.png' %}">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <!-- Main.css -->
      <link rel="stylesheet" type="text/css" href="{% static 'meme/main.css' %}">

      {% if title %}
        <title>ThreeSquare Gag - {{ title }}</title>
      {% else %}
        <title>ThreeSquareGag Meme Page</title>
      {% endif %}
  </head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="/">
          <img src="{% static 'images/Logo_Three_square_gag.png' %}" width="40" height="30" class="d-inline-block align-top navbar-logo" alt="">ThreeSquareGag
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/category/nerd">Nerd</a>
                  <a class="dropdown-item" href="/category/quotes">Quotes</a>
                  <a class="dropdown-item" href="/category/programming">Programming</a>
                  <a class="dropdown-item" href="/category/dailystruggle">Daily struggle</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/search">Meme Explorer <span class="sr-only">(current)</span></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item nav-padding">
                  <a href="{% url 'upload_meme' %}"><button type="button" class="btn btn-outline-light">Upload Meme</button></a>
              </li>
              {% else %}
                <!-- Do not show any upload button if the user is not authenticated -->
              {% endif %}
            </ul>
            <!--right align -->
            <ul class="nav-item navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}"><img class="rounded-circle" src="{{ user.profile.image.url }}" width="25px" height="25px">Profile</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
      <div class="row test">
        <div class="col-md-8">

            <!-- Main content block of base.html -->

            {% block title %} {% endblock %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block mainContent %} {% endblock %}
            {% block searchContent %} {% endblock %}
            {% block searchContent2 %} {% endblock %}

            {%block content2%} {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Popular Memes</h3>
            <p class='text-muted'>Here you can find the most popular memes.
              <ul class="list-group">
                <a class="list-group-item list-group-item-light" href="/mostliked">Most Liked</a>
                <a class="list-group-item list-group-item-light" href="/mostcommented">Most Commented</a>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

memeProject/templates/category_dailystruggle.html
{% extends 'base.html' %}

{% block mainContent %}
<br>
<h2>All #Dailystruggle memes</h2>
<br>
<!-- Displaying all memes that belong to the category 'Daily Struggle' -->
    {% for meme in dailystruggle_list %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>

    {% endfor %}


{% endblock %}

memeProject/templates/category_programming.html
{% extends 'base.html' %}

{% block mainContent %}
<br>
<h2>All #Programming memes</h2>
<br>
<!-- Displaying all memes that belong to the category 'Programming' -->
    {% for meme in programming_list %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>

    {% endfor %}


{% endblock %}

memeProject/templates/category_quotes.html
{% extends 'base.html' %}

{% block mainContent %}
<br>
<h2>All #Quotes memes</h2>
<br>
<!-- Displaying all memes that belong to the category 'Quotes' -->
    {% for meme in quotes_list %}
        <div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>

    {% endfor %}


{% endblock %}

memeProject/templates/count_comments.html
{% extends 'base.html' %}

{% block mainContent %}

{% for meme in commentcount_list %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

memeProject/templates/count_likes.html
{% extends 'base.html' %}

{% block mainContent %}

{% for meme in likecount_list %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

memeProject/templates/meme_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block mainContent %}
<br>
<h2>{{ meme.title }} - {{ title }}</h2>
<br>
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}

        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>
                    {% endif %}
                </form>
                <br>
            {% else %}
                <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
            <hr>
            {% if user.is_authenticated %}
                <h3>Please submit a comment below:</h3>
                <br>
                <form method="post" class="form-group">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    {% if request.user.is_authenticated %}
                        <input type="submit" value="Submit" class="btn btn-outline-success">
                    {% else %}
                        <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                    {% endif %}
                </form>


            {% else %}
                <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <br>
            <div class="main-comment-section">
                {{ comments.count }} Comments
                {% for comment in comments %}

                    <blockquote class="blockquote">

                    <p class="mb-0">{{ comment.content }} </p>
                    <footer class="blockquote-footer">

                    <img class="rounded-circle " src="{{ comment.user.profile.image.url }}"
                    width="30" height="30" alt="Avatar">  {{ comment.user|capfirst}}
                    </footer>
                    </blockquote>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

memeProject/templates/meme_list.html
{% extends 'base.html' %}

{% block mainContent %}

<br>
<h2>Welcome to ThreeSquareGag - Meme feed</h2>
<br>
{% if user.is_authenticated %}
{% else %}
<!-- Do not show any upload button for unauthenticated users -->
<div class="alert alert-success" role="alert">
  In case you want to like or comment our memes, please <a href="{% url 'login' %}">login</a> or create an <a href="{% url 'register' %}">account</a>.
</div>
{% endif %}
<br>
{% for meme in page_obj %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>
{% endfor %}
<nav aria-label="Page navigaton">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

memeProject/templates/meme_list2.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block searchContent2 %}
<br>
<h2>Search memes</h2>
<form method="get">
    {{ myFilter2.form|crispy }}
    <button class="btn btn-primary" type="submit">Search</button>
</form>
<div>
<br>
{% for meme in allmemes %}
<div class="jumbotron">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <h2><a href=/memes/{{meme.id}}>{{ meme.title }}</a></h2>
            {{ meme.timestamp }}
        </div>
        {% if meme.image %}
        <img class="card-img-top" src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ meme.caption }}</h5>
            <p class="card-text">#{{ meme.category }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
                {% csrf_token %}
                <input type="hidden" name="meme_id" value="{{meme.id}}">
                    {% if user not in meme.liked.all %}
                        <button class="btn btn-dark" type="submit">Like</button>
                    {% else %}
                        <button class="btn btn-light" type="submit">Unlike</button>

                    {% endif %}
                </form>
                <br>
            {% else %}
                    <!-- Do not show the like button - user is not authenticated -->
            {% endif %}
            <p><strong>{{ meme.liked.all.count }} likes</strong></p>
        </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

memeProject/templates/meme_list3.html
{% extends 'base.html' %}

{% block searchContent %}
<div>
{% for meme in allmemes %}
<p>
<h3><a href=/memes/{{meme.id}}>{{ meme.title }} </a>
    </h3>

    <p>
        {% if meme.image %}
            <img src="{{ meme.image.url }}" alt="{{ meme.title }}" style="width:480px;">
        {% endif %}
    </p>
    <form action="{% url 'memes:like-meme'%}" method="POST" class=" ui form">
          {% csrf_token %}
              <input type="hidden" name="meme_id" value="{{meme.id}}">
              {% if user not in meme.liked.all %}
                    <button class="ui button positive" type="submit">Like</button>
              {% else %}
                    <button class="ui button negative" type="submit">Unlike</button>
              {% endif %}
          </form>
          <strong>{{ meme.liked.all.count }} likes</strong>
    </p>
<p>{{ meme.caption }}</p>
{% endfor %}
</div>
{% endblock %}

memeProject/templates/search.html
{% extends 'base.html' %}

{% block mainContent %}
<br>
<form method="get">
	{{myFilter.form}}
	<button class="btn btn-primary" type="submit">Search</button>
</form>

{% endblock %}

memeProject/templates/search_product_list.html
{% extends 'base.html' %}

{% block searchContent %}
<form method="get">
				{{myFilter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
    </form>

{%endblock%}
<h1>{{ 'LATEST MEMES' }}</h1



{%block content2%}

<div class="row row-cols-1 row-cols-md-5">
    {% for obj in allProducts %}
    <div class="col mb-4">
        <div class="card">
          <img src="/static/meme_pic.jpeg" class="card-image-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><a href=/products/{{obj.id}}>{{obj.title }} </a>({{ obj.price }})</h5>
              <form action="{% url 'products:like-product'%}" method="POST" class=" ui form"> {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{obj.id}}">
                  {% if user not in obj.liked.all %}
                        <button class="ui button positive" type="submit">Like</button>
                  {% else %}
                        <button class="ui button negative" type="submit">Unlike</button>
                  {% endif %}
              </form>
              <strong>{{ obj.liked.all.count }} likes</strong>
            <p class="card-text">{{obj.summary }}</p>
          </div>
        </div>



    {% endfor%}
</div>

{% endblock %}

memeProject/templates/upload_meme.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!--This is the upload form, that appears after clicking on "Upload Meme"-button-->
{% block mainContent %}
    <br>
    <h2>Upload Meme</h2>
    <hr>
    <br>
    <form method="post" action ="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Upload Meme</button>
    </form>

{% endblock %}

memeProject/templates/uploading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload and Drag& Drop images</title>
    <style>
        #box {
            width: 250px;
            height: 60px;
            padding: 10px;
            margin: 5;
            border: 1px solid #aaaaaa;
        }

        </style>
</head>

<body>
    <p><b>Drag your super fancy meme into this box:</b></p>
 <form action ='.' method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="box" ondrop="drop(event)" ondragover="allowDrop(event)">
            <script>
            function allowDrop(ev)
            {
                ev.preventDefault();
            }

            function drag(ev)
            {
                ev.dataTransfer.setData("text", ev.target.id);
            }

            function drop(ev)
            {
                ev.preventDefault();
                var data = ev.dataTransfer.getData("text");
                ev.target.appendChild(document.getElementById(data));
            }

            </script><br><br><br><p></p>
            <form action="/action_page.php">
                <input type="file" id="myImage" name="imagename">
                </form>
            <label for="imgCaption">Caption:</label><br>
            <input type="text" id="imgCaption" name="imgCaption"><br>
            <label for="imgCategory">Category:</label><br>
            <select id="category"
            <option value="cars">Cars</option>
            <option value="funny">Funny</option>
            <option value="animals">Animals</option>
            <option value="corona">Corona</option>
            </select><br>
            <p></p>
            <form action='actionURL' method='GET'>
                <button type='submit' name="Save" value="Upload" >Upload</button>
                </form>
            </form>


</body>
</html>